### ISSUE TITLE
How to ues code2vec to generate vectors?

### ISSUE THREAD

**Issue by binglinchengxiash** [vector-ai/vectorhub#79]

**Comment by boba-and-beer** [comment]
Hi @binglinchengxiash Code2Vec is a particularly difficult one. Given the number of requirements we had in our code-parsing tool, we had set it as a Docker container to serve as an API. However, since then, we have taken it down due to inactivity with that particular server. If this is something you would like a hosted solution for, please email me at jacky.wong@vctr.ai and we can arrange a meeting to discuss requirements.

**Comment by binglinchengxiash** [comment]
Thank you for replying so quickly.I have use astminer to generate ast paths which fed to code2vec to generate code vectors.Can your API be accepted as ast paths?

**Comment by boba-and-beer** [comment]
ASTs unfortunately are not supported - only code. We utilised a separate internal path-based code representation to extract various code semantics and then trained a neural BOW model across 6 different coding languages for our model (with various tweaks and improvements to improve the vectors -e.g. natural language vectors for documentation sections and code vectors for code sections).

For our docker container, the only level of abstraction we work with is the actual code itself (e.g. what you would see in a normal JavaScript or Python or any of the other 4 languages we trained on).
